In [1]:
import pandas as pd
import numpy as np

### Load the dataset

In [2]:
df = pd.read_csv("Luxury_Housing_Bangalore.csv")

In [3]:
df.shape

(101000, 18)

In [4]:

print(df.columns)

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  str
 1   Micro_Market          101000 non-null  str
 2   Project_Name          101000 non-null  str
 3   Developer_Name        101000 non-null  str
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  str
 6   Ticket_Price_Cr       90981 non-null   str
 7   Transaction_Type      101000 non-null  str
 8   Buyer_Type            101000 non-null  str
 9   Purchase_Quarter      101000 non-null  str
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  str
 13  Sales_Channel         101000 non-null  str
 14  NRI_Buyer             101000 non-null  str
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   str
dtypes: float64(4), int64(1), str(13)
memory usage: 25.7 MB

In [6]:
#checking for null values
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [7]:
#cheching for duplicate values
df.duplicated().sum()

np.int64(1000)

In [8]:
df[df.duplicated()]

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
100000,PROP036224,DOMLUR,Project_223,Embassy,4608.0,5bhk+,6.567529360287568,Secondary,HNI,2024-09-30,8.810723,8.286767,Launch,Broker,yes,9.291593,74,NaN
100001,PROP018298,Domlur,Project_297,Tata Housing,7455.0,5BHK+,NaN,Primary,Other,2024-12-31,4.173285,8.759681,Launch,Online,yes,8.447694,28,Great view from 15th floor.
100002,PROP084496,rajajinagar,Project_495,Prestige,3778.0,4bhk,12.568326856995945,Secondary,NRI,2023-12-31,9.366757,9.049776,Under construction,Broker,no,9.806097,92,Excellent location!
100003,PROP065620,DOMLUR,Project_119,Brigade,NaN,4BHK,₹12.59 Cr,Secondary,Startup Founder,2024-12-31,7.266646,5.718584,Launch,NRI Desk,yes,5.206301,88,Too far from my office.
100004,PROP088229,WHITEFIELD,Project_228,Total Environment,7458.0,4BHK,13.713149406825654,Secondary,HNI,2023-09-30,7.539427,7.310738,Ready to move,Direct,yes,6.533569,69,Connectivity is poor.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [9]:
df = df.drop_duplicates()

In [10]:
df.shape

(100000, 18)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
(df.select_dtypes(include="number") < 0).any()

Unit_Size_Sqft           True
Connectivity_Score      False
Amenity_Score           False
Locality_Infra_Score    False
Avg_Traffic_Time_Min    False
dtype: bool

In [13]:


# Replace invalid unit sizes with NaN
df.loc[df["Unit_Size_Sqft"] <= 0, "Unit_Size_Sqft"] = np.nan

# Fill missing values using median of the same configuration
df["Unit_Size_Sqft"] = (
    df.groupby("Configuration")["Unit_Size_Sqft"]
      .transform(lambda x: x.fillna(x.median()))
)

In [14]:
#Clean text columns
df["Micro_Market"] = df["Micro_Market"].str.title()

In [41]:
df["Configuration"] = (
    df["Configuration"]
    .str.replace(" ", "", regex=False)
    .str.upper()
)

In [42]:
df['Configuration'].value_counts()

Configuration
5BHK+    33536
3BHK     33377
4BHK     33087
Name: count, dtype: int64

In [16]:
df["NRI_Buyer"] = df["NRI_Buyer"].str.title()

In [17]:
df["Ticket_Price_Cr"] = (
    df["Ticket_Price_Cr"]
    .astype(str)
    .str.replace("₹", "", regex=False)
    .str.replace("Cr", "", regex=False)
    .str.strip()
)

df["Ticket_Price_Cr"] = pd.to_numeric(
    df["Ticket_Price_Cr"], 
    errors="coerce"
)

In [18]:
df["Ticket_Price_Cr"].isnull().sum()

np.int64(9913)

In [19]:
(df.select_dtypes(include="number") < 0).any()

Unit_Size_Sqft          False
Ticket_Price_Cr          True
Connectivity_Score      False
Amenity_Score           False
Locality_Infra_Score    False
Avg_Traffic_Time_Min    False
dtype: bool

In [20]:
df.loc[df["Ticket_Price_Cr"] <= 0, "Ticket_Price_Cr"] = np.nan

In [21]:
#filling null values in Ticket_Price_Cr column with mean value of the column
df["Ticket_Price_Cr"].median()

np.float64(12.038618970710633)

In [22]:
numeric_columns = [
    "Ticket_Price_Cr",
    "Unit_Size_Sqft",
    "Amenity_Score"
]

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

df["Buyer_Comments"] = df["Buyer_Comments"].fillna("No comment")

In [23]:
#Convert Purchase_Quarter to Date
df["Purchase_Quarter"].dtype

In [24]:
df["Purchase_Quarter"] = pd.to_datetime(
    df["Purchase_Quarter"],
    errors="coerce"
)

In [25]:
df["Purchase_Year"] = df["Purchase_Quarter"].dt.year

In [26]:
df["Quarter_Number"] = df["Purchase_Quarter"].dt.quarter

In [27]:
df["Quarter_Label"] = (
    df["Purchase_Year"].astype(str)
    + "-Q"
    + df["Quarter_Number"].astype(str)
)

In [28]:
df.shape

(100000, 21)

### Feature Engineering

In [29]:
##Price_per_Sqft
df["Price_per_Sqft"] = (
    (df["Ticket_Price_Cr"] * 10000000) / df["Unit_Size_Sqft"]
).round(2)

In [30]:
df[[
    "Ticket_Price_Cr",
    "Unit_Size_Sqft",
    "Price_per_Sqft"
]].head(10)

   Ticket_Price_Cr  Unit_Size_Sqft  Price_per_Sqft
0        12.750846          4025.0        31679.12
1        16.292152          5760.0        28284.99
2        10.517724          7707.0        13646.98
3         9.396367          6192.0        15175.01
4        15.345392          7147.0        21471.10
5         9.820000          4290.0        22890.44
6        10.896752          6776.0        16081.39
7         9.357539          5763.0        16237.27
8        12.299449          5815.0        21151.25
9         9.193310          8675.0        10597.48

In [31]:
df["Price_per_Sqft"].describe()

count    100000.000000
mean      22916.481295
std       15430.534234
min         995.620000
25%       15624.757500
50%       20051.000000
75%       26533.815000
max      324359.390000
Name: Price_per_Sqft, dtype: float64

In [32]:
(df.select_dtypes(include="number") < 0).any()

Unit_Size_Sqft          False
Ticket_Price_Cr         False
Connectivity_Score      False
Amenity_Score           False
Locality_Infra_Score    False
Avg_Traffic_Time_Min    False
Purchase_Year           False
Quarter_Number          False
Price_per_Sqft          False
dtype: bool

In [33]:
#Nbooking Flag
df["Booking_Flag"] = df["Transaction_Type"].map(
    {"Primary": 1, "Secondary": 0}
)

In [34]:
df["Booking_Flag"].value_counts()

Booking_Flag
1    50013
0    49987
Name: count, dtype: int64

In [35]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
print("Null values:", df.isnull().sum().sum())
print("Duplicate values:", df.duplicated().sum())
print("Negative values:", (df.select_dtypes(include="number") < 0).any().any())

Shape: (100000, 23)
Columns: ['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name', 'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr', 'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter', 'Connectivity_Score', 'Amenity_Score', 'Possession_Status', 'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score', 'Avg_Traffic_Time_Min', 'Buyer_Comments', 'Purchase_Year', 'Quarter_Number', 'Quarter_Label', 'Price_per_Sqft', 'Booking_Flag']
Null values: 0
Duplicate values: 0
Negative values: False

In [43]:
df.to_csv(
    "Luxury_Housing_Bangalore_Cleaned.csv",
    index=False
)

In [44]:
# Load the cleaned CSV
df_check = pd.read_csv("Luxury_Housing_Bangalore_Cleaned.csv")

# Check shape
print("Rows and Columns:", df_check.shape)

# Check first 5 rows
display(df_check.head())

# Check missing values
print("\nMissing Values:")
print(df_check.isnull().sum())

Rows and Columns: (100000, 23)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Purchase_Year,Quarter_Number,Quarter_Label,Price_per_Sqft,Booking_Flag
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,...,Broker,Yes,9.212491,18,Loved the amenities!,2025,1,2025-Q1,31679.12,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,...,NRI Desk,No,7.723898,106,No comment,2024,2,2024-Q2,28284.99,1
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,...,Direct,Yes,6.985493,113,Agent was not responsive.,2023,4,2023-Q4,13646.98,1
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,Online,Yes,6.100929,106,Excellent location!,2024,1,2024-Q1,15175.01,1
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,...,Broker,No,5.312510,18,Too far from my office.,2024,4,2024-Q4,21471.10,0

Missing Values:
Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
Buyer_Comments          0
Purchase_Year           0
Quarter_Number          0
Quarter_Label           0
Price_per_Sqft          0
Booking_Flag            0
dtype: int64

In [45]:
df_check["Configuration"].value_counts()

Configuration
5BHK+    33536
3BHK     33377
4BHK     33087
Name: count, dtype: int64